import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
// You use {} when importing a named export and omit {} for a default export
// because {} tells JavaScript exactly which named item to pull from a module.

import "./globals.css";
// This runs the CSS module to apply its styles globally,
// so there’s no value to import or {} needed.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
